"""empty message

Revision ID: b53b1a678897
Revises: e8f2ebd87033
Create Date: 2017-08-27 15:30:53.591938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b53b1a678897'
down_revision = 'e8f2ebd87033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('create_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_column('article', 'creation_date')
    op.add_column('user', sa.Column('register_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_column('user', 'registration_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registration_date', mysql.TIMESTAMP(), nullable=True))
    op.drop_column('user', 'register_date')
    op.add_column('article', sa.Column('creation_date', mysql.TIMESTAMP(), nullable=True))
    op.drop_column('article', 'create_date')
    # ### end Alembic commands ###
