"""empty message

Revision ID: b595b49924a0
Revises: 17d156f5ed4e
Create Date: 2017-08-27 15:26:46.236287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b595b49924a0'
down_revision = '17d156f5ed4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('create_date', sa.TIMESTAMP(), nullable=True))
    op.drop_column('article', 'creation_date')
    op.add_column('user', sa.Column('register_date', sa.TIMESTAMP(), nullable=True))
    op.drop_column('user', 'registration_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registration_date', mysql.TIMESTAMP(), nullable=True))
    op.drop_column('user', 'register_date')
    op.add_column('article', sa.Column('creation_date', mysql.TIMESTAMP(), nullable=True))
    op.drop_column('article', 'create_date')
    # ### end Alembic commands ###
