"""empty message

Revision ID: ee0435d1d75d
Revises: 07c3530603da
Create Date: 2017-08-27 14:34:12.219879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee0435d1d75d'
down_revision = '07c3530603da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.drop_column('article', 'creation_date')
    op.add_column('user', sa.Column('register_date', sa.DateTime(), nullable=True))
    op.drop_column('user', 'registration_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registration_date', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'register_date')
    op.add_column('article', sa.Column('creation_date', mysql.DATETIME(), nullable=True))
    op.drop_column('article', 'create_date')
    # ### end Alembic commands ###
